openapi: "3.0.2"
info:
  title: Push To Site Server
  version: "1.0"
servers:
  - url: http://localhost:5000
paths:
  /api/v1/shorten:
    post:
      summary: Shortens a url
      operationId: shorten_url
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                longUrl:
                  type: string
                  description: The url you want to shorten
              example:
                longUrl: "http://google.com"
      responses:
        "201":
          description: A url record
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UrlRecord"
  /{slug}:
    get:
      summary: Get a url record by slug
      operationId: get_slug
      parameters:
        - name: slug
          in: path
          description: Slug of the url
          required: true
          schema:
            type: string
            example: aaaaa
      responses:
        "200":
          description: Returns UrlRecord with longUrl
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UrlRecord"
        "404":
          description: Slug not found
          content:
            application/json:
              schema:
                type: string

  /api/v1/dev/entries:
    get:
      summary: Get all url records
      operationId: get_entries
      responses:
        "200":
          description: A list of url records
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UrlRecord"
  /api/v1/dev/reset:
    delete:
      summary: Reset the database
      operationId: reset_database
      responses:
        "200":
          description: Database reset
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    UrlRecord:
      type: object
      properties:
        slug:
          type: string
          description: The slug of the url, it can also be considered its id
        longUrl:
          type: string
          description: The long url of the url record
        hits:
          type: string
          description: The number of times the url record has been accessed (via the slug)
        lastAccessedAt:
          type: string
          format: date-time
          description: The date and time the url record was last accessed
        createdAt:
          type: string
          format: date-time
          description: The date and time the url record was created
        updatedAt:
          type: string
          format: date-time
          description: The date and time the url record was last updated

      example:
        slug: aaaaa
        longUrl: https://www.google.com
        hits: 0
        lastAccessedAt: "2020-01-01T00:00:00.000Z"
        createdAt: "2020-01-01T00:00:00.000Z"
        updatedAt: "2020-01-01T00:00:00.000Z"
